---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kraftnetes.com
  resources:
  - gameservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kraftnetes.com
  resources:
  - gameservers/finalizers
  verbs:
  - update
- apiGroups:
  - kraftnetes.com
  resources:
  - gameservers/status
  verbs:
  - get
  - patch
  - update
