apiVersion: kraftnetes.com/v1alpha1
kind: GameServer
metadata:
  name: minecraft-1
spec:
  game: minecraft
  volumeSize: 15Gi
  filebrowser: true
  profile: vanilla
  env:
    - name: JAVA_OPTS
      value: "-Xmx1G -Xms1G"
    - name: VERSION
      value: '1.21.5'
  resources:
    requests:
      cpu: 1000m
      memory: 1Gi 
    limits:
      cpu: 2000m
      memory: 1200Mi
---
apiVersion: kraftnetes.com/v1alpha1
kind: GameServer
metadata:
  name: minecraft-1
spec:
  game: minecraft
  profile: vanilla
  env:
    - name: JAVA_OPTS
      value: "-Xmx1G -Xms1G"
  resources:
    limits:
      memory: 1400Mi
---