apiVersion: kraftnetes.com/v1alpha1
kind: GameServer
metadata:
  labels:
    app.kubernetes.io/name: k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: gameserver-sample
spec:
  # TODO(user): Add fields here
