name: Build and Publish a Container Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: kraftnetes-operator
  NEW_TAG: main-${{ github.run_id }}

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo "IMAGE_ID=$IMAGE_ID"
          echo "NEW_TAG=$NEW_TAG"
          docker tag $IMAGE_NAME $IMAGE_ID:$NEW_TAG
          docker push $IMAGE_ID:$NEW_TAG
      
      - name: Checkout GitOps Repository
        run: |
          git clone https://x-access-token:${{ secrets.GITOPS_REPO_TOKEN }}@github.com/Kraftnetes/kraftnetes-gitops.git
          cd kraftnetes-gitops
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Run make manifests to generate or update CRDs
        run: make manifests

      - name: Copy CRD files to GitOps Repository
        run: |
          rm -rf kraftnetes-gitops/infra/kraftnetes-operator/crd
          mkdir -p kraftnetes-gitops/infra/kraftnetes-operator/crd
          cp -r config/crd/* kraftnetes-gitops/infra/kraftnetes-operator/crd/

      - name: Update the tag in the GitOps Repository
        run: |
          cd kraftnetes-gitops/infra/kraftnetes-operator/manager
          sed -i "s|newTag: \".*\"|newTag: \"${NEW_TAG}\"|" kustomization.yaml

      - name: Commit and Push Changes
        run: |
          cd kraftnetes-gitops
          git add infra/kraftnetes-operator/manager/kustomization.yaml
          git commit -m "chore: update controller tag to ${NEW_TAG}"
          git push https://x-access-token:${{ secrets.GITOPS_REPO_TOKEN }}@github.com/Kraftnetes/kraftnetes-gitops.git main
